apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: versatil-app
type: Opaque
stringData:
  DATABASE_HOST: 2702251144-project-mysql-server.mysql.database.azure.com
  DATABASE_PORT: 5432
  DATABASE_USER: postgres
  DATABASE_PASSWORD: 12345678
  DATABASE_NAME: versatilDB
  JWT_SECRET: versatil-app
